/** @file
 *   @brief Load time diversification source file
 *   @date 2019-07-14
 *   @version 0.1 *
 *   This file is generated by scala project asm_load_time_diversification. It gives macros for branch table size and MIS amount
 */

#define START_LABEL_MIS_ID 0

/**
 * Number of MISs in shuffle sections
 */
#define MIS_AMOUNT 9

/**
 * Number of entries in branch table
 */
#define BT_SIZE 11
